create extension if not exists pgcrypto;
\n-- Text IDs preserve IDs imported from the previous database.

create table if not exists public.admin_users (id text primary key default gen_random_uuid()::text, auth_user_id uuid unique references auth.users(id) on delete cascade, email text unique not null, name text, role text not null default 'admin' check (role in ('owner','admin')), active boolean not null default true, created_date timestamptz not null default now(), updated_date timestamptz not null default now());
create table if not exists public.cars (id text primary key default gen_random_uuid()::text, name text not null, brand text not null, model text, year integer, price_per_day numeric not null, discount_percentage numeric not null default 0 check (discount_percentage between 0 and 90), status text not null default 'available' check (status in ('available','rented','unavailable')), rented_from date, rented_until date, category text default 'luxury', description_en text, description_ku text, description_ar text, engine text, transmission text default 'automatic', seats integer default 5, images text[] default '{}', video_url text, featured boolean default false, "order" integer default 0, created_date timestamptz not null default now(), updated_date timestamptz not null default now());
create table if not exists public.news (id text primary key default gen_random_uuid()::text, title_en text not null, title_ku text, title_ar text, content_en text, content_ku text, content_ar text, type text not null default 'news', image_url text, active boolean default true, pinned boolean default false, created_date timestamptz not null default now(), updated_date timestamptz not null default now());
create table if not exists public.notify_requests (id text primary key default gen_random_uuid()::text, car_id text references public.cars(id) on delete cascade, car_name text, customer_name text not null, customer_phone text not null, notify_date date, status text default 'pending', created_date timestamptz not null default now(), updated_date timestamptz not null default now());
create table if not exists public.rentals (id text primary key default gen_random_uuid()::text, car_id text references public.cars(id) on delete cascade, car_name text not null, customer_name text not null, customer_phone text, start_date date not null, end_date date not null, status text default 'active', notes text, created_date timestamptz not null default now(), updated_date timestamptz not null default now());
create table if not exists public.reviews (id text primary key default gen_random_uuid()::text, car_id text references public.cars(id) on delete cascade, car_name text, customer_name text not null, rating integer not null check (rating between 1 and 5), comment text not null, images text[] default '{}', approved boolean default false, created_date timestamptz not null default now(), updated_date timestamptz not null default now());
create table if not exists public.otp_codes (id text primary key default gen_random_uuid()::text, email text not null, code text not null, expires_at timestamptz not null, used boolean default false, created_date timestamptz not null default now());
create table if not exists public.site_settings (id text primary key default gen_random_uuid()::text, logo_url text, background_url text, whatsapp_number text not null default '9647509180156', display_phone text default '07509180156', location_url text, instagram_url text, facebook_url text, tiktok_url text, snapchat_url text, telegram_url text, site_name_en text default 'B Car For Rent', site_name_ku text default 'B کار بۆ کرێ', site_name_ar text default 'B كار للإيجار', tagline_en text default 'Precision Luxury on Wheels', tagline_ku text, tagline_ar text, created_date timestamptz not null default now(), updated_date timestamptz not null default now());

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.admin_users where auth_user_id = auth.uid() and active = true) $$;
create or replace function public.is_owner() returns boolean language sql stable security definer set search_path = public as $$ select exists(select 1 from public.admin_users where auth_user_id = auth.uid() and active = true and role = 'owner') $$;

alter table public.admin_users enable row level security; alter table public.cars enable row level security; alter table public.news enable row level security; alter table public.notify_requests enable row level security; alter table public.rentals enable row level security; alter table public.reviews enable row level security; alter table public.site_settings enable row level security; alter table public.otp_codes enable row level security;
create policy "public read cars" on public.cars for select using (true); create policy "admins manage cars" on public.cars for all using (public.is_admin()) with check (public.is_admin());
create policy "public read active news" on public.news for select using (active or public.is_admin()); create policy "admins manage news" on public.news for all using (public.is_admin()) with check (public.is_admin());
create policy "public read approved reviews" on public.reviews for select using (approved or public.is_admin()); create policy "public submit reviews" on public.reviews for insert with check (approved = false); create policy "admins manage reviews" on public.reviews for all using (public.is_admin()) with check (public.is_admin());
create policy "public read settings" on public.site_settings for select using (true); create policy "admins manage settings" on public.site_settings for all using (public.is_admin()) with check (public.is_admin());
create policy "public submit notifications" on public.notify_requests for insert with check (status = 'pending'); create policy "admins manage notifications" on public.notify_requests for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage rentals" on public.rentals for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage otp codes" on public.otp_codes for all using (public.is_admin()) with check (public.is_admin());
create policy "admins read admins" on public.admin_users for select using (public.is_admin()); create policy "owners update admins" on public.admin_users for update using (public.is_owner()) with check (public.is_owner());

insert into storage.buckets (id, name, public) values ('media','media',true) on conflict (id) do update set public = true;
create policy "public read media" on storage.objects for select using (bucket_id = 'media'); create policy "anyone uploads media" on storage.objects for insert with check (bucket_id = 'media'); create policy "admins manage media" on storage.objects for all using (bucket_id = 'media' and public.is_admin()) with check (bucket_id = 'media' and public.is_admin());

-- After creating the first user in Authentication > Users, run:
-- insert into public.admin_users (auth_user_id,email,name,role) values ('AUTH-USER-UUID','you@example.com','Owner','owner');
